//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TherapistDiary.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TherapistDiary.Domain.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Id:&apos;{0}&apos; not found!.
        /// </summary>
        public static string APPOINTMENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("APPOINTMENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start time must be before the end time..
        /// </summary>
        public static string BEGIN_MUST_BE_BEFORE_START {
            get {
                return ResourceManager.GetString("BEGIN_MUST_BE_BEFORE_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete appointment that has already been completed!.
        /// </summary>
        public static string CANNOT_DELETE_APPOINTMENT_IN_PAST {
            get {
                return ResourceManager.GetString("CANNOT_DELETE_APPOINTMENT_IN_PAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date must be today or later..
        /// </summary>
        public static string DATE_MUST_BE_TODAY_OR_LATER {
            get {
                return ResourceManager.GetString("DATE_MUST_BE_TODAY_OR_LATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number you have entered {0} was invalid!.
        /// </summary>
        public static string INVALID_BULGARIAN_PHONE {
            get {
                return ResourceManager.GetString("INVALID_BULGARIAN_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field length must be between {0} and {1} symbols!.
        /// </summary>
        public static string INVALID_FIELD_LENGTH {
            get {
                return ResourceManager.GetString("INVALID_FIELD_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be between {0} and {1}!.
        /// </summary>
        public static string INVALID_NUMBER_VALUE {
            get {
                return ResourceManager.GetString("INVALID_NUMBER_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size must be between &apos;{0}&apos; and &apos;{1}&apos;.
        /// </summary>
        public static string INVALID_PAGE_SIZE {
            get {
                return ResourceManager.GetString("INVALID_PAGE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username: &apos;{0}&apos; or password!.
        /// </summary>
        public static string LOGIN_FAILED {
            get {
                return ResourceManager.GetString("LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token is missing!.
        /// </summary>
        public static string MISSING_REFRESH_TOKEN {
            get {
                return ResourceManager.GetString("MISSING_REFRESH_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page number must be greater than {0}!.
        /// </summary>
        public static string PAGE_NUMBER_MUST_BE_GREATER_THAN {
            get {
                return ResourceManager.GetString("PAGE_NUMBER_MUST_BE_GREATER_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Id:&apos;{0}&apos; not found!.
        /// </summary>
        public static string PATIENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("PATIENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token is expired!.
        /// </summary>
        public static string REFRESH_TOKEN_IS_EXPIRED {
            get {
                return ResourceManager.GetString("REFRESH_TOKEN_IS_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Therapist Id:&apos;{0}&apos; not found!.
        /// </summary>
        public static string THERAPIST_NOT_FOUND {
            get {
                return ResourceManager.GetString("THERAPIST_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve user for refresh token!.
        /// </summary>
        public static string UNABLE_TO_RETRIEVE_USER_FOR_RT {
            get {
                return ResourceManager.GetString("UNABLE_TO_RETRIEVE_USER_FOR_RT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; already exists!.
        /// </summary>
        public static string USER_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("USER_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with Id: &apos;{0}&apos; not found!.
        /// </summary>
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
    }
}
